### ISSUE TITLE
Adapter todo transforms

### ISSUE THREAD

**Issue by tanema** [Shopify/buy-button-js#43]
- [x] apiKey for legacy buy buttons to use the js-buy-sdk
- [x] product component
- [x] collection component
- [x] cart component
- [x] data-display_size
- [x] data-has_image
- [x] data-redirect_to
- [x] data-product_modal
- [x] data-buy_button_text
- [x] data-button_background_color
- [x] data-button_text_color
- [x] data-background_color
- [x] data-show_product_price
- [x] data-show_product_title
- [x] data-buy_button_out_of_stock_text
- [x] data-buy_button_product_unavailable_text
- [x] data-product_title_color
- [x] data-checkout_button_text
- [x] data-text_color
- [x] data-accent_color
- [x] data-cart_title
- [x] data-cart_total_text
- [x] data-discount_notice_text
- [x] data-sticky
- [x] data-empty_cart_text
- [x] data-next_page_button_text
